language: csharp
mono: none
dotnet: 2.0.0
solution: Canducci.ZipCodePostmon.sln
install:
  - dotnet restore Canducci.ZipCodePostmon/Canducci.ZipCodePostmon.csproj  
  - dotnet restore UnitTestZipCode/UnitTestZipCode.csproj
script:
  - dotnet restore Canducci.ZipCodePostmon/Canducci.ZipCodePostmon.csproj  
  - dotnet restore UnitTestZipCode/UnitTestZipCode.csproj